# Generated by Django 4.2.1 on 2023-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funko',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='poleras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='polerones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=500)),
            ],
        ),
    ]
