# Generated by Django 4.2.1 on 2023-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=500)),
                ('tipo_producto', models.CharField(choices=[('F', 'FUNKO'), ('PO', 'POLERON'), ('PA', 'POLERAS'), ('M', 'MAS')], max_length=5)),
            ],
        ),
    ]
