# Generated by Django 4.2.2 on 2023-06-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funko',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='poleras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Polerones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
