# Generated by Django 4.2.1 on 2023-07-07 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_carritocompra_producto_stock_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('bcbfeb81-334f-4bcf-8155-fbe9146836ee'), primary_key=True, serialize=False),
        ),
    ]
