# Generated by Django 4.2.1 on 2023-07-07 01:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_carritocompra_id_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('58b6a978-bca8-470a-9df1-2b81fb076105'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
