# Generated by Django 4.2.1 on 2023-07-07 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_carritocompra_id_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('bc5e7042-c0ae-4a3a-a9a4-481d7dd02367'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elementocarrito',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
