# Generated by Django 4.2.2 on 2023-07-07 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_carritocompra_id_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('6ffdc608-a9fc-4c45-9e00-47d83e391187'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(default=1),
        ),
    ]
