# Generated by Django 4.2.2 on 2023-07-07 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_carritocompra_id_carrito_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='id_carrito',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
